import { fontMono, fontSans } from '@/lib/fonts'
import { cn } from '@/lib/utils'
import Providers from '@/providers'
import type { RootLayoutProps } from '@/types'
import type { Metadata } from 'next'
import '@/styles/globals.css'

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Home',
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={cn(fontSans.variable, fontMono.variable)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
