import SuspendedPostHogPageView from '@/components/posthog/page-view'
import { fontMono, fontSans } from '@/lib/fonts'
import { cn } from '@/lib/utils'
import { ThemeProvider } from '@/providers/next-themes'
import { PostHogProvider } from '@/providers/posthog'
import type { Metadata } from 'next'
import '@/styles/globals.css'

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Home',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={cn(fontSans.variable, fontMono.variable)}>
        <ThemeProvider attribute='class' defaultTheme='dark'>
          <PostHogProvider>
            {children}
            <SuspendedPostHogPageView />
          </PostHogProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
